// <auto-generated />
using System;
using MCDA_Scoring_System.MCDA_Scoring_System.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MCDA_Scoring_System.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260908134511_Seeding")]
    partial class Seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MCDA_Scoring_System.MCDA_Scoring_System.Infrastructure.Data.Entities.Alternative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DecisionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DecisionId");

                    b.ToTable("Alternatives");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DecisionId = 1,
                            Name = "Laptop A"
                        },
                        new
                        {
                            Id = 2,
                            DecisionId = 1,
                            Name = "Laptop B"
                        });
                });

            modelBuilder.Entity("MCDA_Scoring_System.MCDA_Scoring_System.Infrastructure.Data.Entities.AlternativeValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlternativeId")
                        .HasColumnType("int");

                    b.Property<int>("CriterionId")
                        .HasColumnType("int");

                    b.Property<int?>("CriterionOptionId")
                        .HasColumnType("int");

                    b.Property<decimal?>("NumericValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CriterionId");

                    b.HasIndex("CriterionOptionId");

                    b.HasIndex("AlternativeId", "CriterionId")
                        .IsUnique();

                    b.ToTable("AlternativeValues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlternativeId = 1,
                            CriterionId = 1,
                            NumericValue = 56m
                        },
                        new
                        {
                            Id = 2,
                            AlternativeId = 1,
                            CriterionId = 2,
                            CriterionOptionId = 1
                        },
                        new
                        {
                            Id = 3,
                            AlternativeId = 1,
                            CriterionId = 3,
                            CriterionOptionId = 5
                        },
                        new
                        {
                            Id = 4,
                            AlternativeId = 1,
                            CriterionId = 4,
                            NumericValue = 1100m
                        },
                        new
                        {
                            Id = 5,
                            AlternativeId = 1,
                            CriterionId = 5,
                            NumericValue = 880m
                        },
                        new
                        {
                            Id = 6,
                            AlternativeId = 2,
                            CriterionId = 1,
                            NumericValue = 44m
                        },
                        new
                        {
                            Id = 7,
                            AlternativeId = 2,
                            CriterionId = 2,
                            CriterionOptionId = 3
                        },
                        new
                        {
                            Id = 8,
                            AlternativeId = 2,
                            CriterionId = 3,
                            CriterionOptionId = 5
                        },
                        new
                        {
                            Id = 9,
                            AlternativeId = 2,
                            CriterionId = 4,
                            NumericValue = 1050m
                        },
                        new
                        {
                            Id = 10,
                            AlternativeId = 2,
                            CriterionId = 5,
                            NumericValue = 150m
                        });
                });

            modelBuilder.Entity("MCDA_Scoring_System.MCDA_Scoring_System.Infrastructure.Data.Entities.Criterion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CriterionType")
                        .HasColumnType("int");

                    b.Property<int>("DecisionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DecisionId");

                    b.ToTable("Criteria");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CriterionType = 0,
                            DecisionId = 1,
                            Name = "RAM",
                            Weight = 2.1m
                        },
                        new
                        {
                            Id = 2,
                            CriterionType = 1,
                            DecisionId = 1,
                            Name = "Brand",
                            Weight = 1.0m
                        },
                        new
                        {
                            Id = 3,
                            CriterionType = 1,
                            DecisionId = 1,
                            Name = "Performance",
                            Weight = 1.5m
                        },
                        new
                        {
                            Id = 4,
                            CriterionType = 0,
                            DecisionId = 1,
                            Name = "Price",
                            Weight = 3.4m
                        },
                        new
                        {
                            Id = 5,
                            CriterionType = 0,
                            DecisionId = 1,
                            Name = "Storage",
                            Weight = 2.5m
                        });
                });

            modelBuilder.Entity("MCDA_Scoring_System.MCDA_Scoring_System.Infrastructure.Data.Entities.CriterionNumericalRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CriterionId")
                        .HasColumnType("int");

                    b.Property<int?>("Direction")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NumericType")
                        .HasColumnType("int");

                    b.Property<decimal?>("TargetValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CriterionId")
                        .IsUnique();

                    b.ToTable("NumericalCriterionRules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CriterionId = 1,
                            MaxValue = 128m,
                            MinValue = 16m,
                            NumericType = 2,
                            TargetValue = 64m
                        },
                        new
                        {
                            Id = 2,
                            CriterionId = 4,
                            Direction = 0,
                            MaxValue = 1500m,
                            MinValue = 750m,
                            NumericType = 0
                        },
                        new
                        {
                            Id = 3,
                            CriterionId = 5,
                            MaxValue = 1024m,
                            MinValue = 32m,
                            NumericType = 1
                        });
                });

            modelBuilder.Entity("MCDA_Scoring_System.MCDA_Scoring_System.Infrastructure.Data.Entities.CriterionOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CriterionId")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CriterionId", "Value")
                        .IsUnique();

                    b.ToTable("CriterionOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CriterionId = 2,
                            Rank = 1,
                            Value = "Lenovo"
                        },
                        new
                        {
                            Id = 2,
                            CriterionId = 2,
                            Rank = 2,
                            Value = "HP"
                        },
                        new
                        {
                            Id = 3,
                            CriterionId = 2,
                            Rank = 3,
                            Value = "Mac"
                        },
                        new
                        {
                            Id = 4,
                            CriterionId = 3,
                            Rank = 1,
                            Value = "Excellent"
                        },
                        new
                        {
                            Id = 5,
                            CriterionId = 3,
                            Rank = 2,
                            Value = "Good"
                        },
                        new
                        {
                            Id = 6,
                            CriterionId = 3,
                            Rank = 3,
                            Value = "Poor"
                        });
                });

            modelBuilder.Entity("MCDA_Scoring_System.MCDA_Scoring_System.Infrastructure.Data.Entities.Decision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WeightingMethod")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Decisions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Choose a Laptop",
                            WeightingMethod = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Choose a University",
                            WeightingMethod = 0
                        });
                });

            modelBuilder.Entity("MCDA_Scoring_System.MCDA_Scoring_System.Infrastructure.Data.Entities.IntervalRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CriterionNumericalRuleId")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CriterionNumericalRuleId");

                    b.ToTable("NumericRanges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CriterionNumericalRuleId = 3,
                            MaxValue = 1000.0m,
                            MinValue = 570m
                        },
                        new
                        {
                            Id = 2,
                            CriterionNumericalRuleId = 3,
                            MaxValue = 560m,
                            MinValue = 240m
                        },
                        new
                        {
                            Id = 3,
                            CriterionNumericalRuleId = 3,
                            MaxValue = 239m,
                            MinValue = 124m
                        });
                });

            modelBuilder.Entity("MCDA_Scoring_System.MCDA_Scoring_System.Infrastructure.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MCDA_Scoring_System.MCDA_Scoring_System.Infrastructure.Data.Entities.Alternative", b =>
                {
                    b.HasOne("MCDA_Scoring_System.MCDA_Scoring_System.Infrastructure.Data.Entities.Decision", "Decision")
                        .WithMany("Alternatives")
                        .HasForeignKey("DecisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Decision");
                });

            modelBuilder.Entity("MCDA_Scoring_System.MCDA_Scoring_System.Infrastructure.Data.Entities.AlternativeValue", b =>
                {
                    b.HasOne("MCDA_Scoring_System.MCDA_Scoring_System.Infrastructure.Data.Entities.Alternative", "Alternative")
                        .WithMany("AlternativeValues")
                        .HasForeignKey("AlternativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MCDA_Scoring_System.MCDA_Scoring_System.Infrastructure.Data.Entities.Criterion", "Criterion")
                        .WithMany("AlternativeValues")
                        .HasForeignKey("CriterionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MCDA_Scoring_System.MCDA_Scoring_System.Infrastructure.Data.Entities.CriterionOption", "CriterionOption")
                        .WithMany("AlternativeValues")
                        .HasForeignKey("CriterionOptionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Alternative");

                    b.Navigation("Criterion");

                    b.Navigation("CriterionOption");
                });

            modelBuilder.Entity("MCDA_Scoring_System.MCDA_Scoring_System.Infrastructure.Data.Entities.Criterion", b =>
                {
                    b.HasOne("MCDA_Scoring_System.MCDA_Scoring_System.Infrastructure.Data.Entities.Decision", "Decision")
                        .WithMany("Criteria")
                        .HasForeignKey("DecisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Decision");
                });

            modelBuilder.Entity("MCDA_Scoring_System.MCDA_Scoring_System.Infrastructure.Data.Entities.CriterionNumericalRule", b =>
                {
                    b.HasOne("MCDA_Scoring_System.MCDA_Scoring_System.Infrastructure.Data.Entities.Criterion", "Criterion")
                        .WithOne("CriterionNumericalRule")
                        .HasForeignKey("MCDA_Scoring_System.MCDA_Scoring_System.Infrastructure.Data.Entities.CriterionNumericalRule", "CriterionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criterion");
                });

            modelBuilder.Entity("MCDA_Scoring_System.MCDA_Scoring_System.Infrastructure.Data.Entities.CriterionOption", b =>
                {
                    b.HasOne("MCDA_Scoring_System.MCDA_Scoring_System.Infrastructure.Data.Entities.Criterion", "Criterion")
                        .WithMany("CriterionOptions")
                        .HasForeignKey("CriterionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criterion");
                });

            modelBuilder.Entity("MCDA_Scoring_System.MCDA_Scoring_System.Infrastructure.Data.Entities.Decision", b =>
                {
                    b.HasOne("MCDA_Scoring_System.MCDA_Scoring_System.Infrastructure.Data.Entities.User", null)
                        .WithMany("Decisions")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("MCDA_Scoring_System.MCDA_Scoring_System.Infrastructure.Data.Entities.IntervalRange", b =>
                {
                    b.HasOne("MCDA_Scoring_System.MCDA_Scoring_System.Infrastructure.Data.Entities.CriterionNumericalRule", "CriterionNumericalRule")
                        .WithMany("IntervalRanges")
                        .HasForeignKey("CriterionNumericalRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CriterionNumericalRule");
                });

            modelBuilder.Entity("MCDA_Scoring_System.MCDA_Scoring_System.Infrastructure.Data.Entities.Alternative", b =>
                {
                    b.Navigation("AlternativeValues");
                });

            modelBuilder.Entity("MCDA_Scoring_System.MCDA_Scoring_System.Infrastructure.Data.Entities.Criterion", b =>
                {
                    b.Navigation("AlternativeValues");

                    b.Navigation("CriterionNumericalRule");

                    b.Navigation("CriterionOptions");
                });

            modelBuilder.Entity("MCDA_Scoring_System.MCDA_Scoring_System.Infrastructure.Data.Entities.CriterionNumericalRule", b =>
                {
                    b.Navigation("IntervalRanges");
                });

            modelBuilder.Entity("MCDA_Scoring_System.MCDA_Scoring_System.Infrastructure.Data.Entities.CriterionOption", b =>
                {
                    b.Navigation("AlternativeValues");
                });

            modelBuilder.Entity("MCDA_Scoring_System.MCDA_Scoring_System.Infrastructure.Data.Entities.Decision", b =>
                {
                    b.Navigation("Alternatives");

                    b.Navigation("Criteria");
                });

            modelBuilder.Entity("MCDA_Scoring_System.MCDA_Scoring_System.Infrastructure.Data.Entities.User", b =>
                {
                    b.Navigation("Decisions");
                });
#pragma warning restore 612, 618
        }
    }
}
